### ISSUE TITLE
getter-method for variables

### ISSUE THREAD

**Issue by sebastianroming** [ivanrod/polymer-global-variables#1]
Do you have planned to implement a getter method for properties?

**Comment by ivanrod** [comment]
I'm planning to improve the API, meanwhile, you can access to global variables reference in `Polymer.globalsManager.globals` or inside your component `this.globals`.

**Comment by sebastianroming** [comment]
@ivanrod Perfect! So this should work fine for me. Thank you :+1:

**Comment by ivanrod** [comment]
Released version 1.1.0 with `get()` & `getAll()` methods :)

**Comment by sebastianroming** [comment]
@ivanrod awesome - thank you ;-)
